/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.symboleo.SymboleoRuntimeModule;
import org.xtext.example.symboleo.SymboleoStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SymboleoIdeSetup extends SymboleoStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SymboleoRuntimeModule(), new SymboleoIdeModule()));
	}
	
}
