/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.ide;


/**
 * Use this class to register ide components.
 */
public class SymboleoIdeModule extends AbstractSymboleoIdeModule {
}
