/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.symboleo.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.symboleo.symboleo.Enumeration;
import org.xtext.example.symboleo.symboleo.SymboleoPackage;
import org.xtext.example.symboleo.symboleo.enumItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enumeration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symboleo.symboleo.impl.EnumerationImpl#getEnumerationItems <em>Enumeration Items</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumerationImpl extends DomainConceptImpl implements Enumeration
{
  /**
   * The cached value of the '{@link #getEnumerationItems() <em>Enumeration Items</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerationItems()
   * @generated
   * @ordered
   */
  protected EList<enumItem> enumerationItems;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumerationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.ENUMERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<enumItem> getEnumerationItems()
  {
    if (enumerationItems == null)
    {
      enumerationItems = new EObjectContainmentEList<enumItem>(enumItem.class, this, SymboleoPackage.ENUMERATION__ENUMERATION_ITEMS);
    }
    return enumerationItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.ENUMERATION__ENUMERATION_ITEMS:
        return ((InternalEList<?>)getEnumerationItems()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.ENUMERATION__ENUMERATION_ITEMS:
        return getEnumerationItems();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.ENUMERATION__ENUMERATION_ITEMS:
        getEnumerationItems().clear();
        getEnumerationItems().addAll((Collection<? extends enumItem>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.ENUMERATION__ENUMERATION_ITEMS:
        getEnumerationItems().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.ENUMERATION__ENUMERATION_ITEMS:
        return enumerationItems != null && !enumerationItems.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //EnumerationImpl
