/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.symboleo.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.symboleo.symboleo.Atom;
import org.xtext.example.symboleo.symboleo.Negation;
import org.xtext.example.symboleo.symboleo.SymboleoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Negation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symboleo.symboleo.impl.NegationImpl#isNegated <em>Negated</em>}</li>
 *   <li>{@link org.xtext.example.symboleo.symboleo.impl.NegationImpl#getAtomicExpression <em>Atomic Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NegationImpl extends MinimalEObjectImpl.Container implements Negation
{
  /**
   * The default value of the '{@link #isNegated() <em>Negated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNegated()
   * @generated
   * @ordered
   */
  protected static final boolean NEGATED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNegated() <em>Negated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNegated()
   * @generated
   * @ordered
   */
  protected boolean negated = NEGATED_EDEFAULT;

  /**
   * The cached value of the '{@link #getAtomicExpression() <em>Atomic Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtomicExpression()
   * @generated
   * @ordered
   */
  protected Atom atomicExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NegationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.NEGATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isNegated()
  {
    return negated;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNegated(boolean newNegated)
  {
    boolean oldNegated = negated;
    negated = newNegated;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.NEGATION__NEGATED, oldNegated, negated));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Atom getAtomicExpression()
  {
    return atomicExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtomicExpression(Atom newAtomicExpression, NotificationChain msgs)
  {
    Atom oldAtomicExpression = atomicExpression;
    atomicExpression = newAtomicExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.NEGATION__ATOMIC_EXPRESSION, oldAtomicExpression, newAtomicExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtomicExpression(Atom newAtomicExpression)
  {
    if (newAtomicExpression != atomicExpression)
    {
      NotificationChain msgs = null;
      if (atomicExpression != null)
        msgs = ((InternalEObject)atomicExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.NEGATION__ATOMIC_EXPRESSION, null, msgs);
      if (newAtomicExpression != null)
        msgs = ((InternalEObject)newAtomicExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.NEGATION__ATOMIC_EXPRESSION, null, msgs);
      msgs = basicSetAtomicExpression(newAtomicExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.NEGATION__ATOMIC_EXPRESSION, newAtomicExpression, newAtomicExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.NEGATION__ATOMIC_EXPRESSION:
        return basicSetAtomicExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.NEGATION__NEGATED:
        return isNegated();
      case SymboleoPackage.NEGATION__ATOMIC_EXPRESSION:
        return getAtomicExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.NEGATION__NEGATED:
        setNegated((Boolean)newValue);
        return;
      case SymboleoPackage.NEGATION__ATOMIC_EXPRESSION:
        setAtomicExpression((Atom)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.NEGATION__NEGATED:
        setNegated(NEGATED_EDEFAULT);
        return;
      case SymboleoPackage.NEGATION__ATOMIC_EXPRESSION:
        setAtomicExpression((Atom)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.NEGATION__NEGATED:
        return negated != NEGATED_EDEFAULT;
      case SymboleoPackage.NEGATION__ATOMIC_EXPRESSION:
        return atomicExpression != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (negated: ");
    result.append(negated);
    result.append(')');
    return result.toString();
  }

} //NegationImpl
