/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.symboleo.parser.antlr.internal.InternalSymboleoParser;
import org.xtext.example.symboleo.services.SymboleoGrammarAccess;

public class SymboleoParser extends AbstractAntlrParser {

	@Inject
	private SymboleoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSymboleoParser createParser(XtextTokenStream stream) {
		return new InternalSymboleoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SymboleoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SymboleoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
