/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SymboleoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/symboleo/parser/antlr/internal/InternalSymboleo.tokens");
	}
}
