/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symboleo.symboleo.Atom#getEventProposition <em>Event Proposition</em>}</li>
 *   <li>{@link org.xtext.example.symboleo.symboleo.Atom#getSituationProposition <em>Situation Proposition</em>}</li>
 *   <li>{@link org.xtext.example.symboleo.symboleo.Atom#getPoint <em>Point</em>}</li>
 *   <li>{@link org.xtext.example.symboleo.symboleo.Atom#getInterval <em>Interval</em>}</li>
 *   <li>{@link org.xtext.example.symboleo.symboleo.Atom#getBool <em>Bool</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getAtom()
 * @model
 * @generated
 */
public interface Atom extends EObject
{
  /**
   * Returns the value of the '<em><b>Event Proposition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Proposition</em>' containment reference.
   * @see #setEventProposition(EventProp)
   * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getAtom_EventProposition()
   * @model containment="true"
   * @generated
   */
  EventProp getEventProposition();

  /**
   * Sets the value of the '{@link org.xtext.example.symboleo.symboleo.Atom#getEventProposition <em>Event Proposition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Proposition</em>' containment reference.
   * @see #getEventProposition()
   * @generated
   */
  void setEventProposition(EventProp value);

  /**
   * Returns the value of the '<em><b>Situation Proposition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Situation Proposition</em>' containment reference.
   * @see #setSituationProposition(SitProp)
   * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getAtom_SituationProposition()
   * @model containment="true"
   * @generated
   */
  SitProp getSituationProposition();

  /**
   * Sets the value of the '{@link org.xtext.example.symboleo.symboleo.Atom#getSituationProposition <em>Situation Proposition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Situation Proposition</em>' containment reference.
   * @see #getSituationProposition()
   * @generated
   */
  void setSituationProposition(SitProp value);

  /**
   * Returns the value of the '<em><b>Point</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point</em>' containment reference.
   * @see #setPoint(Point)
   * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getAtom_Point()
   * @model containment="true"
   * @generated
   */
  Point getPoint();

  /**
   * Sets the value of the '{@link org.xtext.example.symboleo.symboleo.Atom#getPoint <em>Point</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point</em>' containment reference.
   * @see #getPoint()
   * @generated
   */
  void setPoint(Point value);

  /**
   * Returns the value of the '<em><b>Interval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interval</em>' containment reference.
   * @see #setInterval(Interval)
   * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getAtom_Interval()
   * @model containment="true"
   * @generated
   */
  Interval getInterval();

  /**
   * Sets the value of the '{@link org.xtext.example.symboleo.symboleo.Atom#getInterval <em>Interval</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interval</em>' containment reference.
   * @see #getInterval()
   * @generated
   */
  void setInterval(Interval value);

  /**
   * Returns the value of the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' attribute.
   * @see #setBool(String)
   * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getAtom_Bool()
   * @model
   * @generated
   */
  String getBool();

  /**
   * Sets the value of the '{@link org.xtext.example.symboleo.symboleo.Atom#getBool <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' attribute.
   * @see #getBool()
   * @generated
   */
  void setBool(String value);

} // Atom
