/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.symboleo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Junction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.symboleo.symboleo.Junction#getNegativeAtoms <em>Negative Atoms</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getJunction()
 * @model
 * @generated
 */
public interface Junction extends EObject
{
  /**
   * Returns the value of the '<em><b>Negative Atoms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.symboleo.symboleo.Negation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negative Atoms</em>' containment reference list.
   * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getJunction_NegativeAtoms()
   * @model containment="true"
   * @generated
   */
  EList<Negation> getNegativeAtoms();

} // Junction
