/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Name</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.symboleo.symboleo.SymboleoPackage#getTypeName()
 * @model
 * @generated
 */
public interface TypeName extends EObject
{
} // TypeName
