/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.symboleo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSymboleoScopeProvider extends DelegatingScopeProvider {
}
